[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
tokio = { version = "1", features = ["full"] }
common = { path = "../common" }
clap = { version = "4.5.42", features = ["derive"] }
miniquad = "0.4.8"
bytemuck = "1.23.1"
