[package]
name = "launcher"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
anyhow = "1.0.98"
eframe = "0.32.0"
tokio = { version = "1", features = ["full"] }
local-ip-address = "0.6.5"
common = { path = "../common" }
zip = "0.6"
reqwest = "0.12.22"
