[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
tokio = { version = "1", features = ["full"] }
common = { path = "../common" }
clap = { version = "4.5.42", features = ["derive"] }
